### ISSUE TITLE
Figure out solution for repository storage of storage-heavy media files

### ISSUE THREAD

**Issue by sbenthall** [yrevocnu/culthq-game#4]
The 0.2 version of CultHQ: Escape has:
 - ~40 MB of music files
 - ~30 MB of image files

The total assets accumulated for the game so far (i.e., for content not yet released in the 0.2 version but in progress) is perhaps 10x this size. 

I'm reluctant to include these media files in the GitHub repository because:
 - I'm worried about hitting disk space limits that would force us into a different [billing bracket](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-packages)
 - Version control on big files is, in my understanding, a recipe for even bigger repositories
 - Some perhaps dubious copyright status of raw images before transformation into "fair use" derivatives

So I think it would be better to host the media files elsewhere, perhaps in Google Drive, and then have a simple installer script that collects the media and puts it in the right place.

cc @benheller for sanity check on this approach

**Comment by benheller** [comment]
I'd be happy to let us use the S3 bucket where we store our Discourse backups. It will be inexpensive.

**Comment by sbenthall** [comment]
Thank you! I'd prefer to start with Google Drive because I have plenty of space there (we could go to 10 GBs for example, no problem) and because I think it's somewhat more accessible to non-technical contributors.

I will email you a link to the directory where the music and images are and I've updated the README to instruct how to use these files.
